[package]
name = "actix_vite_starter"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
actix-web-lab = { version = "0.23.0", features = ["spa"] }
actix-web = "4.9.0"
log = "0.4.22"
